// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies_API_DJM.Models;

namespace Movies_API_DJM.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20191113073006_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Movies_API_DJM.Models.Movies", b =>
                {
                    b.Property<string>("imdbID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Plot");

                    b.Property<string>("Rated");

                    b.Property<string>("Title");

                    b.Property<int>("Year");

                    b.HasKey("imdbID");

                    b.ToTable("FavMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
